CREATE TABLE if not exists FILE_IMPORT (
   file_import_id BIGINT NOT NULL,
   username VARCHAR(128) NOT NULL,
   filename VARCHAR(100) NOT NULL,
   size_in_kb VARCHAR(200) NULL,
   file_extension VARCHAR(50) NOT NULL,
   separator VARCHAR(1) NOT NULL,
   layout_id BIGINT NOT NULL,
   operation_date TIMESTAMP NOT NULL,
   PRIMARY KEY (file_import_id)
);

CREATE SEQUENCE IF NOT EXISTS FILEIMPORT_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE if not exists FILE_IMPORT_DATA (
   file_import_data_id BIGINT NOT NULL,
   FILE_IMPORT_ID BIGINT NOT NULL,
   row CLOB(30K) NOT NULL,
   operation_date TIMESTAMP NOT NULL,
   PRIMARY KEY (file_import_data_id)
);

CREATE SEQUENCE IF NOT EXISTS FILEIMPORTDATA_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE if not exists LAYOUT (
   layout_id INTEGER NOT NULL,
   code VARCHAR(10) NOT NULL,
   name VARCHAR(20) NOT NULL,
   description VARCHAR(50) NULL,
   extension VARCHAR(4) NOT NULL,
   version VARCHAR(10) NOT NULL,
   value CLOB(30K) NOT NULL,
   PRIMARY KEY (layout_id)
);

CREATE SEQUENCE IF NOT EXISTS LAYOUT_SEQ START WITH 1 INCREMENT BY 1;